import{a as h,i,S as L}from"./assets/vendor-C4-ZuMk8.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const y of n.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&o(y)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const E="46595467-38d51347a919535f7c3759bfb";async function g(t,s=1,r=60){const o=`https://pixabay.com/api/?key=${E}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${s}&per_page=${r}`;try{const e=await h.get(o);return{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){return console.error("Error:",e),{images:[],totalHits:0}}}function f(t){const s=document.getElementById("image-gallery");s.innerHTML="",t.forEach(r=>{const o=document.createElement("a");o.href=r.largeImageURL,o.classList.add("gallery-item"),o.innerHTML=`
      <img src="${r.webformatURL}" alt="${r.tags}">
      <div class="image-info">
        <p><strong>Downloads:</strong> ${r.downloads}</p>
        <p><strong>Likes:</strong> ${r.likes}</p>
        <p><strong>Views:</strong> ${r.views}</p>
        
      </div>
    `,s.appendChild(o)})}function b(){const t=document.getElementById("image-gallery");t.innerHTML=""}let l=1,m="",u=0,c=0,p;const a=document.createElement("button");a.textContent="Load more";a.style.display="none";a.classList.add("load-more-btn");document.body.appendChild(a);a.addEventListener("click",async function(){l+=1;const{images:t}=await g(m,l);t.length>0&&(f(t),c+=t.length,p.refresh(),c>=u&&(a.style.display="none",i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})))});const d=document.createElement("div");d.classList.add("loader");d.innerHTML='<div class="lds-dual-ring"></div>';document.body.appendChild(d);d.style.display="none";document.addEventListener("DOMContentLoaded",function(){document.getElementById("search-form").addEventListener("submit",async function(s){s.preventDefault();const r=document.getElementById("search-input"),o=r.value.trim();if(o===""){i.error({title:"Error",message:"Please enter a valid search query!"});return}b(),l=1,m=o,d.style.display="block";try{const{images:e,totalHits:n}=await g(o,l);u=n,c=e.length,e.length>0?(f(e),p=new L(".gallery a",{captionsData:"alt",captionDelay:250}),c<u?a.style.display="block":(a.style.display="none",i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))):(i.error({title:"Error",message:"Sorry, no images matching your search query. Please try again!"}),a.style.display="none")}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error("Error:",e)}finally{d.style.display="none",r.value=""}})});a.addEventListener("click",async function(){l+=1;const{images:t}=await g(m,l);if(t.length>0){const s=document.querySelector(".gallery"),{height:r}=s.firstElementChild.getBoundingClientRect();f(t),c+=t.length,p.refresh(),window.scrollBy({top:r*2,behavior:"smooth"}),c>=u&&(a.style.display="none",i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}});
//# sourceMappingURL=index.js.map
