import{a as h,i,S as L}from"./assets/vendor-C4-ZuMk8.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const y of o.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&r(y)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const b="46595467-38d51347a919535f7c3759bfb";async function g(t,n=1,a=15){const r=`https://pixabay.com/api/?key=${b}&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=${a}`;try{const e=await h.get(r);return{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){return console.error("Error:",e),{images:[],totalHits:0}}}function f(t){const n=document.getElementById("image-gallery"),a=t.map(r=>`
      <a href="${r.largeImageURL}" class="gallery-item">
        <img src="${r.webformatURL}" alt="${r.tags}">
        <div class="image-info">
          <p><strong>Downloads:</strong> ${r.downloads}</p>
          <p><strong>Likes:</strong> ${r.likes}</p>
          <p><strong>Views:</strong> ${r.views}</p>
        </div>
      </a>
    `).join("");n.insertAdjacentHTML("beforeend",a)}function v(){const t=document.getElementById("image-gallery");t.innerHTML=""}let l=1,m="",u=0,c=0,p;const s=document.createElement("button");s.textContent="Load more";s.style.display="none";s.classList.add("load-more-btn");document.body.appendChild(s);s.addEventListener("click",async function(){l+=1;const{images:t}=await g(m,l);t.length>0&&(f(t),c+=t.length,p.refresh(),c>=u&&(s.style.display="none",i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})))});const d=document.createElement("div");d.classList.add("loader");d.innerHTML='<div class="lds-dual-ring"></div>';document.body.appendChild(d);d.style.display="none";document.addEventListener("DOMContentLoaded",function(){document.getElementById("search-form").addEventListener("submit",async function(n){n.preventDefault();const a=document.getElementById("search-input"),r=a.value.trim();if(r===""){i.error({title:"Error",message:"Please enter a valid search query!"});return}v(),l=1,m=r,d.style.display="block";try{const{images:e,totalHits:o}=await g(r,l);u=o,c=e.length,e.length>0?(f(e),p=new L(".gallery a",{captionsData:"alt",captionDelay:250}),c<u?s.style.display="block":(s.style.display="none",i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))):(i.error({title:"Error",message:"Sorry, no images matching your search query. Please try again!"}),s.style.display="none")}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later."}),console.error("Error:",e)}finally{d.style.display="none",a.value=""}})});s.addEventListener("click",async function(){l+=1;const{images:t}=await g(m,l);if(t.length>0){const n=document.querySelector(".gallery"),{height:a}=n.firstElementChild.getBoundingClientRect();f(t),c+=t.length,p.refresh(),window.scrollBy({top:a*2,behavior:"smooth"}),c>=u&&(s.style.display="none",i.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}});
//# sourceMappingURL=index.js.map
